In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_excel('employee_data_messy.xlsx')
df=pd.DataFrame(data)
print(df)

      Employee_ID      Full_Name  Age  Gender  Department   Hire_Date Salary  \
0        EMP01287     Hiro Singh   46    Male          HR  2014-04-29  25786
1        EMP03698   Fatima Smith   27  Female          IT  2023-03-18  64787
2        EMP05345   Omar Johnson  NaN  Female  Operations  2008-08-19  52766
3        EMP01452   Lucas Wilson   64  Female          HR  2014-11-21  54123
4        EMP01620    Lucas Smith   62  Female         NaN  2016-05-22  42492
...           ...            ...  ...     ...         ...         ...    ...
10145    EMP01100  Fatima Garcia   43   Other   Marketing  2014-07-01    NaN
10146    EMP02515      Hiro Chen  NaN  Female       Legal  2012-01-11  55594
10147    EMP06638    Maya Martin   54     NaN         NaN  2015-06-27  43511
10148    EMP02576   Priya Wilson   61  Female          IT  2011-04-09  81794
10149    EMP07337   Priya Wilson   36    Male       Legal  2022-03-12    NaN

      Performance_Rating
0                      2
1                      3
2                      4
3                      3
4                      3
...                  ...
10145                  4
10146                  3
10147                  4
10148                  4
10149                  2

[10150 rows x 8 columns]

In [ ]:
df.head(10)

,Employee_ID,Full_Name,Age,Gender,Department,Hire_Date,Salary,Performance_Rating
0,EMP01287,Hiro Singh,46,Male,HR,2014-04-29,25786,2
1,EMP03698,Fatima Smith,27,Female,IT,2023-03-18,64787,3
2,EMP05345,Omar Johnson,NaN,Female,Operations,2008-08-19,52766,4
3,EMP01452,Lucas Wilson,64,Female,HR,2014-11-21,54123,3
4,EMP01620,Lucas Smith,62,Female,NaN,2016-05-22,42492,3
5,EMP06699,Emma Martin,61,Female,Legal,2020-09-18,54056,3
6,EMP02086,Aisha Johnson,53,Male,Legal,2005-02-01,46931,3
7,EMP03870,Olivia Kim,59,Male,HR,2014-06-28,61592,NaN
8,EMP06047,Omar Singh,46,M,Sales,2020-03-13,70908,3
9,EMP08522,Wei Singh,44,Female,HR,2023-06-13,20000,4

In [ ]:
df.columns

Index(['Employee_ID', 'Full_Name', 'Age', 'Gender', 'Department', 'Hire_Date',
       'Salary', 'Performance_Rating'],
      dtype='object')

In [ ]:
df['Gender'] = df['Gender'].replace({
    'Male': 'M',
    'Female': 'F'
})

In [ ]:
df

,Employee_ID,Full_Name,Age,Gender,Department,Hire_Date,Salary,Performance_Rating
0,EMP01287,Hiro Singh,46,M,HR,2014-04-29,25786,2
1,EMP03698,Fatima Smith,27,F,IT,2023-03-18,64787,3
2,EMP05345,Omar Johnson,NaN,F,Operations,2008-08-19,52766,4
3,EMP01452,Lucas Wilson,64,F,HR,2014-11-21,54123,3
4,EMP01620,Lucas Smith,62,F,NaN,2016-05-22,42492,3
...,...,...,...,...,...,...,...,...
10145,EMP01100,Fatima Garcia,43,Other,Marketing,2014-07-01,NaN,4
10146,EMP02515,Hiro Chen,NaN,F,Legal,2012-01-11,55594,3
10147,EMP06638,Maya Martin,54,NaN,NaN,2015-06-27,43511,4
10148,EMP02576,Priya Wilson,61,F,IT,2011-04-09,81794,4
10149,EMP07337,Priya Wilson,36,M,Legal,2022-03-12,NaN,2

In [ ]:
df['Gender'].isnull().sum()

np.int64(794)

In [ ]:
df['Gender']=df['Gender'].replace('Other','O')
df

,Employee_ID,Full_Name,Age,Gender,Department,Hire_Date,Salary,Performance_Rating
0,EMP01287,Hiro Singh,46,M,HR,2014-04-29,25786,2
1,EMP03698,Fatima Smith,27,F,IT,2023-03-18,64787,3
2,EMP05345,Omar Johnson,NaN,F,Operations,2008-08-19,52766,4
3,EMP01452,Lucas Wilson,64,F,HR,2014-11-21,54123,3
4,EMP01620,Lucas Smith,62,F,NaN,2016-05-22,42492,3
...,...,...,...,...,...,...,...,...
10145,EMP01100,Fatima Garcia,43,O,Marketing,2014-07-01,NaN,4
10146,EMP02515,Hiro Chen,NaN,F,Legal,2012-01-11,55594,3
10147,EMP06638,Maya Martin,54,NaN,NaN,2015-06-27,43511,4
10148,EMP02576,Priya Wilson,61,F,IT,2011-04-09,81794,4
10149,EMP07337,Priya Wilson,36,M,Legal,2022-03-12,NaN,2

In [ ]:
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])
df['Gender']

0        M
1        F
2        F
3        F
4        F
        ..
10145    O
10146    F
10147    F
10148    F
10149    M
Name: Gender, Length: 10150, dtype: object

In [ ]:
df.isnull().sum()

Employee_ID            117
Full_Name              394
Age                   1056
Gender                   0
Department             665
Hire_Date              871
Salary                1355
Performance_Rating    1867
dtype: int64

In [ ]:
df = df.dropna(subset=['Employee_ID']).copy()

In [ ]:
df.isnull().sum()

Employee_ID              0
Full_Name              389
Age                   1043
Gender                   0
Department             656
Hire_Date              863
Salary                1341
Performance_Rating    1845
dtype: int64

In [ ]:
df

,Employee_ID,Full_Name,Age,Gender,Department,Hire_Date,Salary,Performance_Rating
0,EMP01287,Hiro Singh,46,M,HR,2014-04-29,25786,2
1,EMP03698,Fatima Smith,27,F,IT,2023-03-18,64787,3
2,EMP05345,Omar Johnson,NaN,F,Operations,2008-08-19,52766,4
3,EMP01452,Lucas Wilson,64,F,HR,2014-11-21,54123,3
4,EMP01620,Lucas Smith,62,F,NaN,2016-05-22,42492,3
...,...,...,...,...,...,...,...,...
10145,EMP01100,Fatima Garcia,43,O,Marketing,2014-07-01,NaN,4
10146,EMP02515,Hiro Chen,NaN,F,Legal,2012-01-11,55594,3
10147,EMP06638,Maya Martin,54,F,NaN,2015-06-27,43511,4
10148,EMP02576,Priya Wilson,61,F,IT,2011-04-09,81794,4
10149,EMP07337,Priya Wilson,36,M,Legal,2022-03-12,NaN,2

In [ ]:
df[['Age', 'Salary', 'Performance_Rating']].describe()

         Age  Salary  Performance_Rating
count   8990    8692                8188
unique   107    7596                   6
top       59      -1                   3
freq     225     207                3204

In [ ]:
df['Age']=pd.to_numeric(df['Age'],errors='coerce')
df['Age']=df['Age'].fillna(df['Age'].median())
df['Age']

/tmp/ipykernel_1972/3744105660.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=pd.to_numeric(df['Age'],errors='coerce')
/tmp/ipykernel_1972/3744105660.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].fillna(df['Age'].median())

0        46.0
1        27.0
2        43.0
3        64.0
4        62.0
         ...
10145    43.0
10146    43.0
10147    54.0
10148    61.0
10149    36.0
Name: Age, Length: 10033, dtype: float64

In [ ]:
df.isnull().sum()

Employee_ID              0
Full_Name              389
Age                      0
Gender                   0
Department             656
Hire_Date              863
Salary                1341
Performance_Rating    1845
dtype: int64

In [ ]:
df['Salary']

0        25786
1        64787
2        52766
3        54123
4        42492
         ...
10145      NaN
10146    55594
10147    43511
10148    81794
10149      NaN
Name: Salary, Length: 10033, dtype: object

In [ ]:
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
min_salary = df['Salary'].min()
min_salary

-1.0

In [ ]:
max_salary=df['Salary'].max()
max_salary

150130.0

In [ ]:
df['Salary'] = df['Salary'].replace(-1, np.nan)

In [ ]:
min_salary = df['Salary'].min()
min_salary

20000.0

In [ ]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
df['Salary']

0        25786.0
1        64787.0
2        52766.0
3        54123.0
4        42492.0
          ...
10145    59894.0
10146    55594.0
10147    43511.0
10148    81794.0
10149    59894.0
Name: Salary, Length: 10033, dtype: float64

In [ ]:
df.isnull().sum()

Employee_ID              0
Full_Name              389
Age                      0
Gender                   0
Department             656
Hire_Date              863
Salary                   0
Performance_Rating    1845
dtype: int64

In [ ]:
df = df.dropna(subset=['Full_Name']).copy()
df

,Employee_ID,Full_Name,Age,Gender,Department,Hire_Date,Salary,Performance_Rating
0,EMP01287,Hiro Singh,46.0,M,HR,2014-04-29,25786.0,2
1,EMP03698,Fatima Smith,27.0,F,IT,2023-03-18,64787.0,3
2,EMP05345,Omar Johnson,43.0,F,Operations,2008-08-19,52766.0,4
3,EMP01452,Lucas Wilson,64.0,F,HR,2014-11-21,54123.0,3
4,EMP01620,Lucas Smith,62.0,F,NaN,2016-05-22,42492.0,3
...,...,...,...,...,...,...,...,...
10145,EMP01100,Fatima Garcia,43.0,O,Marketing,2014-07-01,59894.0,4
10146,EMP02515,Hiro Chen,43.0,F,Legal,2012-01-11,55594.0,3
10147,EMP06638,Maya Martin,54.0,F,NaN,2015-06-27,43511.0,4
10148,EMP02576,Priya Wilson,61.0,F,IT,2011-04-09,81794.0,4
10149,EMP07337,Priya Wilson,36.0,M,Legal,2022-03-12,59894.0,2

In [ ]:
df['Performance_Rating'] = pd.to_numeric(df['Performance_Rating'], errors='coerce')
df['Performance_Rating'] = df['Performance_Rating'].fillna(df['Performance_Rating'].median())
df['Performance_Rating']

/tmp/ipykernel_1972/1867051543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Performance_Rating'] = pd.to_numeric(df['Performance_Rating'], errors='coerce')
/tmp/ipykernel_1972/1867051543.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Performance_Rating'] = df['Performance_Rating'].fillna(df['Performance_Rating'].median())

0        2.0
1        3.0
2        4.0
3        3.0
4        3.0
        ...
10145    4.0
10146    3.0
10147    4.0
10148    4.0
10149    2.0
Name: Performance_Rating, Length: 9644, dtype: float64

In [ ]:
df.isnull().sum()

Employee_ID             0
Full_Name               0
Age                     0
Gender                  0
Department            637
Hire_Date             827
Salary                  0
Performance_Rating      0
dtype: int64

In [ ]:
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])
df['Department']

0                HR
1                IT
2        Operations
3                HR
4             Sales
            ...
10145     Marketing
10146         Legal
10147         Sales
10148            IT
10149         Legal
Name: Department, Length: 9644, dtype: object

In [ ]:
df = df.dropna(subset=['Hire_Date'])

In [ ]:
df.isnull().sum()

Employee_ID           0
Full_Name             0
Age                   0
Gender                0
Department            0
Hire_Date             0
Salary                0
Performance_Rating    0
dtype: int64

In [ ]:
df.drop_duplicates()

,Employee_ID,Full_Name,Age,Gender,Department,Hire_Date,Salary,Performance_Rating
0,EMP01287,Hiro Singh,46.0,M,HR,2014-04-29,25786.0,2.0
1,EMP03698,Fatima Smith,27.0,F,IT,2023-03-18,64787.0,3.0
2,EMP05345,Omar Johnson,43.0,F,Operations,2008-08-19,52766.0,4.0
3,EMP01452,Lucas Wilson,64.0,F,HR,2014-11-21,54123.0,3.0
4,EMP01620,Lucas Smith,62.0,F,Sales,2016-05-22,42492.0,3.0
...,...,...,...,...,...,...,...,...
10145,EMP01100,Fatima Garcia,43.0,O,Marketing,2014-07-01,59894.0,4.0
10146,EMP02515,Hiro Chen,43.0,F,Legal,2012-01-11,55594.0,3.0
10147,EMP06638,Maya Martin,54.0,F,Sales,2015-06-27,43511.0,4.0
10148,EMP02576,Priya Wilson,61.0,F,IT,2011-04-09,81794.0,4.0
10149,EMP07337,Priya Wilson,36.0,M,Legal,2022-03-12,59894.0,2.0